name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
    - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu 環境で実行

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4

      - name: Node.js のセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 依存関係のインストール
        run: npm install

      - name: Docusaurus のビルド
        run: npm run build

      - name: ビルド成果物の保存（オプション）
        uses: actions/upload-artifact@v4
        with:
          name: skinview3d-embed
          path: build  # `build` ディレクトリを保存